# Generated by Django 5.2.1 on 2025-05-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NganhDaoTao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_nganh",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã Ngành"
                    ),
                ),
                (
                    "ten_nganh",
                    models.CharField(max_length=255, verbose_name="Tên Ngành"),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Ngành đào tạo",
                "verbose_name_plural": "Các ngành đào tạo",
            },
        ),
        migrations.CreateModel(
            name="DanhMucKienThuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_danh_muc",
                    models.CharField(
                        max_length=255, verbose_name="Tên danh mục kiến thức"
                    ),
                ),
                (
                    "ma_danh_muc",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Mã danh mục",
                    ),
                ),
                (
                    "mo_ta",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mô tả danh mục"
                    ),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "danh_muc_cha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="danh_muc_con",
                        to="daotao.danhmuckienthuc",
                        verbose_name="Danh mục cha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục Kiến thức",
                "verbose_name_plural": "Các Danh mục Kiến thức",
                "ordering": ["danh_muc_cha__ten_danh_muc", "ten_danh_muc"],
            },
        ),
        migrations.CreateModel(
            name="DonViDaoTao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_don_vi",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã đơn vị"
                    ),
                ),
                (
                    "ten_don_vi",
                    models.CharField(max_length=255, verbose_name="Tên đơn vị đào tạo"),
                ),
                (
                    "mo_ta",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mô tả đơn vị"
                    ),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "don_vi_cha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="don_vi_con",
                        to="daotao.donvidaotao",
                        verbose_name="Đơn vị cha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn vị Đào tạo",
                "verbose_name_plural": "Các Đơn vị Đào tạo",
                "ordering": ["don_vi_cha__ten_don_vi", "ten_don_vi"],
            },
        ),
        migrations.CreateModel(
            name="ChuongTrinhDaoTao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_nganh_ctdt",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã ngành CTĐT"
                    ),
                ),
                (
                    "ten_nganh_ctdt",
                    models.CharField(max_length=255, verbose_name="Tên ngành CTĐT"),
                ),
                (
                    "trinh_do_dao_tao",
                    models.CharField(
                        choices=[
                            ("DH", "Đại học"),
                            ("THS", "Thạc sĩ"),
                            ("TS", "Tiến sĩ"),
                            ("CD", "Cao đẳng"),
                        ],
                        default="CD",
                        max_length=3,
                        verbose_name="Trình độ đào tạo",
                    ),
                ),
                (
                    "hinh_thuc_dao_tao",
                    models.CharField(
                        choices=[
                            ("CQ", "Chính quy"),
                            ("VLVH", "Vừa làm vừa học"),
                            ("TX", "Từ xa"),
                        ],
                        default="CQ",
                        max_length=4,
                        verbose_name="Hình thức đào tạo",
                    ),
                ),
                (
                    "thoi_gian_dao_tao",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Thời gian đào tạo"
                    ),
                ),
                (
                    "mo_ta_chung",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mô tả chung CTĐT"
                    ),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "don_vi_quan_ly",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="daotao.donvidaotao",
                        verbose_name="Đơn vị quản lý",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chương trình Đào tạo",
                "verbose_name_plural": "Các Chương trình Đào tạo",
                "ordering": ["ten_nganh_ctdt"],
            },
        ),
        migrations.CreateModel(
            name="HocPhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_hoc_phan",
                    models.CharField(max_length=20, verbose_name="Mã học phần"),
                ),
                (
                    "ten_hoc_phan",
                    models.CharField(max_length=255, verbose_name="Tên học phần"),
                ),
                (
                    "tin_chi_ly_thuyet",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số tín chỉ lý thuyết"
                    ),
                ),
                (
                    "tin_chi_thuc_hanh",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số tín chỉ thực hành"
                    ),
                ),
                (
                    "so_gio_ly_thuyet",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số giờ lý thuyết"
                    ),
                ),
                (
                    "so_gio_thuc_hanh",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số giờ thực hành"
                    ),
                ),
                (
                    "so_gio_tu_hoc",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Số giờ tự học/khác",
                    ),
                ),
                (
                    "hoc_phan_bat_buoc",
                    models.BooleanField(
                        default=True, verbose_name="Là học phần bắt buộc?"
                    ),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "chuong_trinh_dao_tao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hoc_phan_lien_quan",
                        to="daotao.chuongtrinhdaotao",
                        verbose_name="Chương trình đào tạo",
                    ),
                ),
                (
                    "danh_muc_kien_thuc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="daotao.danhmuckienthuc",
                        verbose_name="Thuộc Danh mục kiến thức",
                    ),
                ),
            ],
            options={
                "verbose_name": "Học phần",
                "verbose_name_plural": "Các Học phần",
                "ordering": ["ma_hoc_phan"],
                "unique_together": {("chuong_trinh_dao_tao", "ma_hoc_phan")},
            },
        ),
    ]
