# Generated by Django 5.2.1 on 2025-05-28 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hocphan",
            options={
                "ordering": ["ma_hoc_phan"],
                "verbose_name": "Học phần (Thư viện chung)",
                "verbose_name_plural": "Các Học phần (Thư viện chung)",
            },
        ),
        migrations.AlterModelOptions(
            name="nganhdaotao",
            options={
                "verbose_name": "Ngành đào tạo (Danh mục)",
                "verbose_name_plural": "Các ngành đào tạo (Danh mục)",
            },
        ),
        migrations.AlterUniqueTogether(
            name="hocphan",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="chuong_trinh_tham_khao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Chương trình đào tạo tham khảo"
            ),
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="dieu_kien_tot_nghiep",
            field=models.TextField(
                blank=True, null=True, verbose_name="Điều kiện tốt nghiệp"
            ),
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="doi_tuong_tuyen_sinh",
            field=models.TextField(
                blank=True, null=True, verbose_name="Đối tượng tuyển sinh"
            ),
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="nganh_hoc_chung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="daotao.nganhdaotao",
                verbose_name="Thuộc Ngành học (chung)",
            ),
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="so_tin_chi_yeu_cau",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tổng số tín chỉ yêu cầu"
            ),
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="ten_tieng_anh",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tên chương trình đào tạo (Tiếng Anh)",
            ),
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="van_bang_tot_nghiep",
            field=models.CharField(
                blank=True,
                choices=[("CN", "Cử nhân"), ("KS", "Kỹ sư"), ("BS", "Bác sĩ")],
                max_length=3,
                null=True,
                verbose_name="Văn bằng tốt nghiệp",
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="mo_ta_hoc_phan",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mô tả chung học phần"
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="so_gio_ly_thuyet_goc",
            field=models.PositiveIntegerField(default=0, verbose_name="Số giờ LT gốc"),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="so_gio_thuc_hanh_goc",
            field=models.PositiveIntegerField(default=0, verbose_name="Số giờ TH gốc"),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="so_gio_tu_hoc_goc",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Số giờ tự học/khác (gốc)",
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="tin_chi_ly_thuyet_goc",
            field=models.PositiveIntegerField(default=0, verbose_name="Số TC LT gốc"),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="tin_chi_thuc_hanh_goc",
            field=models.PositiveIntegerField(default=0, verbose_name="Số TC TH gốc"),
        ),
        migrations.AlterField(
            model_name="chuongtrinhdaotao",
            name="ma_nganh_ctdt",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Mã chương trình/ngành đào tạo"
            ),
        ),
        migrations.AlterField(
            model_name="chuongtrinhdaotao",
            name="ten_nganh_ctdt",
            field=models.CharField(
                max_length=255, verbose_name="Tên chương trình đào tạo (Tiếng Việt)"
            ),
        ),
        migrations.AlterField(
            model_name="chuongtrinhdaotao",
            name="thoi_gian_dao_tao",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Thời gian đào tạo (ví dụ: 3.5 năm)",
            ),
        ),
        migrations.AlterField(
            model_name="chuongtrinhdaotao",
            name="trinh_do_dao_tao",
            field=models.CharField(
                choices=[
                    ("DH", "Đại học"),
                    ("CD", "Cao đẳng"),
                    ("THS", "Thạc sĩ"),
                    ("TS", "Tiến sĩ"),
                ],
                default="DH",
                max_length=3,
                verbose_name="Trình độ đào tạo",
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="ma_hoc_phan",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Mã học phần (chung)"
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="ngay_cap_nhat",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Ngày cập nhật học phần chung"
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="ngay_tao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Ngày tạo học phần chung"
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="ten_hoc_phan",
            field=models.CharField(max_length=255, verbose_name="Tên học phần (chung)"),
        ),
        migrations.AlterField(
            model_name="nganhdaotao",
            name="ma_nganh",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Mã Ngành (Danh mục)"
            ),
        ),
        migrations.AlterField(
            model_name="nganhdaotao",
            name="ten_nganh",
            field=models.CharField(max_length=255, verbose_name="Tên Ngành (Danh mục)"),
        ),
        migrations.CreateModel(
            name="ChiTietHocPhanTrongCTDT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "la_bat_buoc",
                    models.BooleanField(
                        default=True, verbose_name="Bắt buộc trong CTĐT này?"
                    ),
                ),
                (
                    "hoc_ky_du_kien",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Học kỳ dự kiến"
                    ),
                ),
                (
                    "tin_chi_ly_thuyet_apdung",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Số TC LT áp dụng"
                    ),
                ),
                (
                    "tin_chi_thuc_hanh_apdung",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Số TC TH áp dụng"
                    ),
                ),
                (
                    "so_gio_ly_thuyet_apdung",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Số giờ LT áp dụng"
                    ),
                ),
                (
                    "so_gio_thuc_hanh_apdung",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Số giờ TH áp dụng"
                    ),
                ),
                (
                    "so_gio_tu_hoc_apdung",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Số giờ tự học áp dụng"
                    ),
                ),
                (
                    "ghi_chu_trong_ctdt",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú riêng cho CTĐT"
                    ),
                ),
                (
                    "ngay_tao_lien_ket",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày thêm vào CTĐT"
                    ),
                ),
                (
                    "ngay_cap_nhat_lien_ket",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ngày cập nhật trong CTĐT"
                    ),
                ),
                (
                    "chuong_trinh_dao_tao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daotao.chuongtrinhdaotao",
                        verbose_name="Chương trình đào tạo",
                    ),
                ),
                (
                    "danh_muc_kien_thuc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="daotao.danhmuckienthuc",
                        verbose_name="Phân loại trong CTĐT này",
                    ),
                ),
                (
                    "hoc_phan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daotao.hocphan",
                        verbose_name="Học phần (từ thư viện)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết Học phần trong CTĐT",
                "verbose_name_plural": "Các Chi tiết Học phần trong CTĐT",
                "ordering": ["chuong_trinh_dao_tao", "hoc_phan__ma_hoc_phan"],
                "unique_together": {("chuong_trinh_dao_tao", "hoc_phan")},
            },
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="hoc_phan_trong_chuong_trinh",
            field=models.ManyToManyField(
                related_name="co_trong_cac_ctdt",
                through="daotao.ChiTietHocPhanTrongCTDT",
                through_fields=("chuong_trinh_dao_tao", "hoc_phan"),
                to="daotao.hocphan",
                verbose_name="Các học phần trong chương trình",
            ),
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="chuong_trinh_dao_tao",
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="danh_muc_kien_thuc",
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="ghi_chu",
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="hoc_phan_bat_buoc",
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="so_gio_ly_thuyet",
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="so_gio_thuc_hanh",
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="so_gio_tu_hoc",
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="tin_chi_ly_thuyet",
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="tin_chi_thuc_hanh",
        ),
    ]
