# Generated by Django 5.2.1 on 2025-05-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0002_alter_hocphan_options_alter_nganhdaotao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChuanDauRa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_cdr",
                    models.CharField(
                        max_length=20, verbose_name="Mã chuẩn đầu ra (PLO)"
                    ),
                ),
                ("noi_dung", models.TextField(verbose_name="Nội dung chuẩn đầu ra")),
                (
                    "loai_cdr",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KT", "Về kiến thức"),
                            ("KN", "Về kỹ năng"),
                            ("TD", "Về thái độ/Năng lực tự chủ và trách nhiệm"),
                            ("KHAC", "Khác"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="Loại chuẩn đầu ra",
                    ),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "chuong_trinh_dao_tao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chuan_dau_ra_ctdt",
                        to="daotao.chuongtrinhdaotao",
                        verbose_name="Chương trình đào tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chuẩn Đầu Ra CTĐT",
                "verbose_name_plural": "Các Chuẩn Đầu Ra CTĐT",
                "ordering": ["chuong_trinh_dao_tao", "ma_cdr"],
                "unique_together": {("chuong_trinh_dao_tao", "ma_cdr")},
            },
        ),
        migrations.CreateModel(
            name="DeCuongHocPhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_de_cuong",
                    models.CharField(
                        max_length=255, verbose_name="Tên/Phiên bản đề cương"
                    ),
                ),
                (
                    "muc_tieu_hoc_phan",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mục tiêu học phần"
                    ),
                ),
                (
                    "chuan_dau_ra_hoc_phan",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Chuẩn đầu ra của học phần (CLO)",
                    ),
                ),
                (
                    "tom_tat_noi_dung",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tóm tắt nội dung học phần"
                    ),
                ),
                (
                    "phuong_phap_day_hoc",
                    models.TextField(
                        blank=True, null=True, verbose_name="Phương pháp dạy và học"
                    ),
                ),
                (
                    "nhiem_vu_sinh_vien",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nhiệm vụ của sinh viên"
                    ),
                ),
                (
                    "thang_diem_danh_gia",
                    models.TextField(
                        blank=True, null=True, verbose_name="Thang điểm/Cách đánh giá"
                    ),
                ),
                (
                    "tai_lieu_hoc_tap",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tài liệu học tập"
                    ),
                ),
                (
                    "ngay_ban_hanh",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày ban hành"
                    ),
                ),
                (
                    "la_phien_ban_moi_nhat",
                    models.BooleanField(
                        default=True, verbose_name="Là phiên bản mới nhất?"
                    ),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "hoc_phan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="de_cuong_chi_tiet",
                        to="daotao.hocphan",
                        verbose_name="Học phần",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đề cương Học phần",
                "verbose_name_plural": "Các Đề cương Học phần",
                "ordering": ["hoc_phan", "-ngay_ban_hanh"],
            },
        ),
        migrations.CreateModel(
            name="MaTranCDR_CTHP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "muc_do_dong_gop",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Introduced"),
                            ("R", "Reinforced"),
                            ("M", "Mastery"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "chi_tiet_hoc_phan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daotao.chitiethocphantrongctdt",
                    ),
                ),
                (
                    "chuan_dau_ra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daotao.chuandaura",
                    ),
                ),
            ],
            options={
                "unique_together": {("chuan_dau_ra", "chi_tiet_hoc_phan")},
            },
        ),
        migrations.AddField(
            model_name="chitiethocphantrongctdt",
            name="chuan_dau_ra_lien_quan",
            field=models.ManyToManyField(
                related_name="hoc_phan_chi_tiet_lien_quan",
                through="daotao.MaTranCDR_CTHP",
                to="daotao.chuandaura",
                verbose_name="Các CĐR CTĐT được học phần này đóng góp",
            ),
        ),
    ]
