# Generated by Django 5.2.1 on 2025-05-30 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0003_chuandaura_decuonghocphan_matrancdr_cthp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decuonghocphan",
            name="chuan_dau_ra_hoc_phan",
        ),
        migrations.CreateModel(
            name="ChuanDauRaHocPhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_clo",
                    models.CharField(
                        max_length=20, verbose_name="Mã Chuẩn đầu ra học phần (CLO)"
                    ),
                ),
                (
                    "noi_dung",
                    models.TextField(verbose_name="Nội dung Chuẩn đầu ra học phần"),
                ),
                (
                    "dong_tu_bloom",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Động từ Bloom chính",
                    ),
                ),
                (
                    "muc_do_bloom",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REM", "Nhận biết (Remembering)"),
                            ("UND", "Thông hiểu (Understanding)"),
                            ("APP", "Vận dụng (Applying)"),
                            ("ANA", "Phân tích (Analyzing)"),
                            ("EVA", "Đánh giá (Evaluating)"),
                            ("CRE", "Sáng tạo (Creating)"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Mức độ theo thang Bloom",
                    ),
                ),
                (
                    "loai_clo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KT", "Kiến thức"),
                            ("KN", "Kỹ năng"),
                            ("TD", "Thái độ/Năng lực tự chủ và trách nhiệm"),
                            ("KHAC", "Khác"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="Loại Chuẩn đầu ra học phần",
                    ),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "de_cuong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chuan_dau_ra_cua_de_cuong",
                        to="daotao.decuonghocphan",
                        verbose_name="Thuộc Đề cương học phần",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chuẩn Đầu Ra Học Phần (CLO)",
                "verbose_name_plural": "Các Chuẩn Đầu Ra Học Phần (CLO)",
                "ordering": ["de_cuong", "ma_clo"],
                "unique_together": {("de_cuong", "ma_clo")},
            },
        ),
    ]
