# Generated by Django 5.2.1 on 2025-05-31 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0004_remove_decuonghocphan_chuan_dau_ra_hoc_phan_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chuandaura",
            options={
                "ordering": ["chuong_trinh_dao_tao", "ma_cdr"],
                "verbose_name": "Chuẩn Đầu Ra CTĐT (PLO)",
                "verbose_name_plural": "Các Chuẩn Đầu Ra CTĐT (PLO)",
            },
        ),
        migrations.CreateModel(
            name="MucTieuDaoTao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_muc_tieu",
                    models.CharField(max_length=20, verbose_name="Mã mục tiêu (PO)"),
                ),
                (
                    "noi_dung",
                    models.TextField(verbose_name="Nội dung mục tiêu đào tạo"),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "chuong_trinh_dao_tao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muc_tieu_dao_tao_ctdt",
                        to="daotao.chuongtrinhdaotao",
                        verbose_name="Chương trình đào tạo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chuandaura",
            name="dap_ung_muc_tieu",
            field=models.ManyToManyField(
                blank=True,
                related_name="cac_cdr_dap_ung",
                to="daotao.muctieudaotao",
                verbose_name="Đáp ứng Mục tiêu Đào tạo (PO)",
            ),
        ),
    ]
