# Generated by Django 5.2.1 on 2025-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0005_alter_chuandaura_options_muctieudaotao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chitiethocphantrongctdt",
            name="chuan_dau_ra_lien_quan",
        ),
        migrations.AddField(
            model_name="chitiethocphantrongctdt",
            name="so_tiet_ly_thuyet_online",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Số tiết Lý thuyết Online",
            ),
        ),
    ]
