# Generated by Django 5.2.1 on 2025-05-31 06:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daotao",
            "0006_remove_chitiethocphantrongctdt_chuan_dau_ra_lien_quan_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decuonghocphan",
            options={
                "ordering": ["hoc_phan", "-ngay_ban_hanh"],
                "verbose_name": "Phiên bản Đề cương Học phần",
                "verbose_name_plural": "Các Phiên bản Đề cương Học phần",
            },
        ),
        migrations.RemoveField(
            model_name="decuonghocphan",
            name="la_phien_ban_moi_nhat",
        ),
        migrations.RemoveField(
            model_name="decuonghocphan",
            name="ngay_cap_nhat",
        ),
        migrations.RemoveField(
            model_name="decuonghocphan",
            name="ngay_tao",
        ),
        migrations.RemoveField(
            model_name="decuonghocphan",
            name="ten_de_cuong",
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="la_phien_ban_hien_hanh",
            field=models.BooleanField(
                default=False, verbose_name="Là phiên bản hiện hành?"
            ),
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="ly_do_cap_nhat",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Lý do cập nhật/Nội dung thay đổi chính",
            ),
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="ngay_cap_nhat_record",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Ngày cập nhật bản ghi"
            ),
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="ngay_tao_record",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Ngày tạo bản ghi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="so_phien_ban",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Số hiệu phiên bản (nếu có)",
            ),
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="ten_de_cuong_phien_ban",
            field=models.CharField(
                default="Phiên bản không tên",
                max_length=255,
                verbose_name="Tên/Ghi chú cho phiên bản đề cương này",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="decuonghocphan",
            name="hoc_phan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_de_cuong",
                to="daotao.hocphan",
                verbose_name="Học phần",
            ),
        ),
        migrations.AlterField(
            model_name="decuonghocphan",
            name="muc_tieu_hoc_phan",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Mục tiêu học phần (của phiên bản này)",
            ),
        ),
        migrations.AlterField(
            model_name="decuonghocphan",
            name="ngay_ban_hanh",
            field=models.DateField(
                default=datetime.date(2025, 5, 31),
                verbose_name="Ngày ban hành/Hiệu lực",
            ),
            preserve_default=False,
        ),
    ]
