# Generated by Django 5.2.1 on 2025-06-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0007_alter_decuonghocphan_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matrancdr_cthp",
            options={
                "verbose_name": "Ma trận CĐR CTĐT - Học phần",
                "verbose_name_plural": "Các Ma trận CĐR CTĐT - Học phần",
            },
        ),
        migrations.AlterModelOptions(
            name="muctieudaotao",
            options={
                "verbose_name": "Mục tiêu Đào tạo CTĐT (PO)",
                "verbose_name_plural": "Các Mục tiêu Đào tạo CTĐT (PO)",
            },
        ),
        migrations.AddField(
            model_name="hocphan",
            name="don_vi_quan_ly_goc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="daotao.donvidaotao",
                verbose_name="Đơn vị quản lý gốc (MaDV)",
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="khong_tinh_diem_tb",
            field=models.BooleanField(
                default=False, verbose_name="Không tính ĐTB? (KhgTinhDTB=1)"
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="la_hoc_phan_tu_chon",
            field=models.BooleanField(
                default=False, verbose_name="Là học phần tự chọn? (IsMHTN=1)"
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="so_tiet_tong_cong",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tổng số tiết học (SoTietMH)"
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="so_tin_chi_ects",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Số tín chỉ ECTS (SoTinChiEU)"
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="ten_tieng_anh",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tên học phần (Tiếng Anh - TenMHEg)",
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="tong_so_tin_chi_goc",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tổng số TC gốc (SoTinChi)"
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="ma_hoc_phan",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Mã học phần (MaMH)"
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="ngay_cap_nhat",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Ngày cập nhật bản ghi"
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="ngay_tao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Ngày tạo bản ghi"
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="ten_hoc_phan",
            field=models.CharField(max_length=255, verbose_name="Tên học phần (TenMH)"),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="tin_chi_ly_thuyet_goc",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Số TC Lý thuyết gốc"
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="tin_chi_thuc_hanh_goc",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Số TC Thực hành gốc"
            ),
        ),
    ]
