# Generated by Django 5.2.1 on 2025-07-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0009_chuongtrinhdaotao_ly_do_thay_doi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="ghi_chu_ctdt",
            field=models.TextField(blank=True, null=True, verbose_name="Ghi chú CTĐT"),
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="ngay_ban_hanh_qd",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày ban hành Quyết định"
            ),
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="so_quyet_dinh_ban_hanh",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Số Quyết định ban hành",
            ),
        ),
    ]
