# Generated by Django 5.2.1 on 2025-07-24 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0011_chitiethocphantrongctdt_so_gio_bai_tap_apdung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hocphan",
            name="hoc_phan_tien_quyet",
            field=models.ManyToManyField(
                blank=True, to="daotao.hocphan", verbose_name="Học phần tiên quyết"
            ),
        ),
        migrations.CreateModel(
            name="HinhThucDanhGia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_hinh_thuc",
                    models.CharField(
                        max_length=255,
                        verbose_name="Tên hình thức đánh giá (ví dụ: Bài tập lớn, Thi giữa kỳ)",
                    ),
                ),
                (
                    "loai_danh_gia",
                    models.CharField(
                        choices=[
                            ("QT", "Đánh giá quá trình"),
                            ("CK", "Đánh giá cuối kỳ"),
                        ],
                        max_length=2,
                        verbose_name="Loại đánh giá",
                    ),
                ),
                (
                    "ty_le_diem",
                    models.PositiveIntegerField(verbose_name="Tỷ lệ điểm (%)"),
                ),
                (
                    "chuan_dau_ra_danh_gia",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hinh_thuc_danh_gia_lien_quan",
                        to="daotao.chuandaurahocphan",
                        verbose_name="Chuẩn đầu ra được đánh giá",
                    ),
                ),
                (
                    "de_cuong_hoc_phan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hinh_thuc_danh_gia",
                        to="daotao.decuonghocphan",
                        verbose_name="Thuộc Đề cương học phần",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hình thức Đánh giá",
                "verbose_name_plural": "Các Hình thức Đánh giá",
                "ordering": ["de_cuong_hoc_phan", "loai_danh_gia"],
            },
        ),
        migrations.CreateModel(
            name="NoiDungChiTietDeCuong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tuan_hoc_hoac_chu_de",
                    models.CharField(
                        max_length=255, verbose_name="Tuần học hoặc Chủ đề"
                    ),
                ),
                (
                    "noi_dung_giang_day",
                    models.TextField(verbose_name="Nội dung giảng dạy"),
                ),
                (
                    "so_gio_ly_thuyet",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số giờ lý thuyết"
                    ),
                ),
                (
                    "so_gio_thuc_hanh",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số giờ thực hành"
                    ),
                ),
                (
                    "so_gio_tu_hoc",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số giờ tự học"
                    ),
                ),
                (
                    "chuan_dau_ra_lien_quan",
                    models.ManyToManyField(
                        blank=True,
                        related_name="noi_dung_hoc_tap",
                        to="daotao.chuandaurahocphan",
                        verbose_name="Chuẩn đầu ra liên quan",
                    ),
                ),
                (
                    "de_cuong_hoc_phan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noi_dung_chi_tiet",
                        to="daotao.decuonghocphan",
                        verbose_name="Thuộc Đề cương học phần",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nội dung Chi tiết Đề cương",
                "verbose_name_plural": "Các Nội dung Chi tiết Đề cương",
                "ordering": ["de_cuong_hoc_phan", "tuan_hoc_hoac_chu_de"],
            },
        ),
    ]
