# Generated by Django 5.2.1 on 2025-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0012_hocphan_hoc_phan_tien_quyet_hinhthucdanhgia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decuonghocphan",
            name="cac_yeu_cau_khac",
            field=models.TextField(
                blank=True, null=True, verbose_name="Các yêu cầu khác của học phần"
            ),
        ),
        migrations.AddField(
            model_name="hocphan",
            name="hoc_phan_song_hanh",
            field=models.ManyToManyField(
                blank=True,
                related_name="la_song_hanh_voi",
                to="daotao.hocphan",
                verbose_name="Học phần song hành",
            ),
        ),
        migrations.AlterField(
            model_name="hocphan",
            name="hoc_phan_tien_quyet",
            field=models.ManyToManyField(
                blank=True,
                related_name="la_tien_quyet_cho",
                to="daotao.hocphan",
                verbose_name="Học phần tiên quyết",
            ),
        ),
    ]
