# Generated by Django 5.2.1 on 2025-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0013_decuonghocphan_cac_yeu_cau_khac_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hocphan",
            name="hoc_phan_song_hanh",
        ),
        migrations.RemoveField(
            model_name="hocphan",
            name="hoc_phan_tien_quyet",
        ),
        migrations.AddField(
            model_name="chitiethocphantrongctdt",
            name="hoc_phan_song_hanh",
            field=models.ManyToManyField(
                blank=True,
                related_name="la_song_hanh_voi",
                to="daotao.chitiethocphantrongctdt",
                verbose_name="Học phần song hành trong CTĐT này",
            ),
        ),
        migrations.AddField(
            model_name="chitiethocphantrongctdt",
            name="hoc_phan_tien_quyet",
            field=models.ManyToManyField(
                blank=True,
                related_name="la_tien_quyet_cho",
                to="daotao.chitiethocphantrongctdt",
                verbose_name="Học phần tiên quyết trong CTĐT này",
            ),
        ),
    ]
