# Generated by Django 5.2.1 on 2025-07-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0014_remove_hocphan_hoc_phan_song_hanh_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chuongtrinhdaotao",
            options={
                "ordering": ["ten_nganh_ctdt"],
                "permissions": [
                    ("can_approve_ctdt", "Có thể phê duyệt Chương trình Đào tạo"),
                    ("can_reject_ctdt", "Có thể yêu cầu chỉnh sửa/từ chối CTĐT"),
                    ("can_submit_for_approval", "Có thể gửi duyệt CTĐT"),
                    ("can_create_new_version", "Có thể tạo phiên bản mới cho CTĐT"),
                    ("can_archive_ctdt", "Có thể lưu trữ một CTĐT cũ"),
                    (
                        "can_manage_program_structure",
                        "Có thể quản lý cấu trúc CTĐT (PO, PLO, học phần)",
                    ),
                ],
                "verbose_name": "Chương trình Đào tạo",
                "verbose_name_plural": "Các Chương trình Đào tạo",
            },
        ),
    ]
