# Generated by Django 5.2.1 on 2025-07-25 08:37

from django.db import migrations

def setup_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Define groups and their permissions
    groups_permissions = {
        'Ban Giám hiệu': [
            'can_approve_ctdt',
            'can_reject_ctdt',
            'view_chuongtrinhdaotao',
        ],
        'Hội đồng Khoa học & Đào tạo (HĐKH&ĐT)': [
            'can_approve_ctdt',
            'can_reject_ctdt',
            'view_chuongtrinhdaotao',
        ],
        'Đơn vị chuyên môn (ĐVCM - ví dụ: Trưởng khoa/Viện)': [
            'add_chuongtrinhdaotao',
            'change_chuongtrinhdaotao',
            'delete_chuongtrinhdaotao',
            'can_submit_for_approval',
            'can_create_new_version',
            'can_manage_program_structure',
            'view_chuongtrinhdaotao',
        ],
        'Trung tâm Học liệu - Điều phối (TT.HL-DH)': [
            'view_chuongtrinhdaotao',
        ],
        'Người dùng cơ bản (Regular User - ví dụ: Giảng viên)': [
            'view_chuongtrinhdaotao',
        ]
    }

    for group_name, permission_codenames in groups_permissions.items():
        group, created = Group.objects.get_or_create(name=group_name)
        permissions = Permission.objects.filter(codename__in=permission_codenames)
        group.permissions.set(permissions)
        if created:
            print(f'Created group: {group_name}')
        else:
            print(f'Updated group: {group_name}')


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0015_alter_chuongtrinhdaotao_options"),
    ]

    operations = [
        migrations.RunPython(setup_groups),
    ]
