# Generated by Django 5.2.1 on 2025-07-31 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0016_setup_groups_and_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiangVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ho", models.CharField(max_length=100, verbose_name="Họ")),
                ("ten", models.CharField(max_length=50, verbose_name="Tên")),
                (
                    "ngay_sinh",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                (
                    "so_cccd_ho_chieu",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Số CCCD/Hộ chiếu",
                    ),
                ),
                (
                    "ma_can_bo",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã cán bộ"
                    ),
                ),
                (
                    "quoc_tich",
                    models.CharField(
                        default="Việt Nam", max_length=100, verbose_name="Quốc tịch"
                    ),
                ),
                (
                    "gioi_tinh",
                    models.CharField(
                        choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("Khác", "Khác")],
                        max_length=10,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "chuc_vu_cong_tac",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Chức vụ công tác",
                    ),
                ),
                (
                    "chuc_danh_khoa_hoc",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Chức danh khoa học",
                    ),
                ),
                (
                    "trinh_do_dao_tao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Trình độ đào tạo (cao nhất)",
                    ),
                ),
                (
                    "chuyen_mon_dao_tao",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Chuyên môn đào tạo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "dien_thoai",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Điện thoại"
                    ),
                ),
                (
                    "trang_thai_lam_viec",
                    models.CharField(
                        choices=[
                            ("Đang làm việc", "Đang làm việc"),
                            ("Nghỉ hưu", "Nghỉ hưu"),
                            ("Nghỉ việc", "Nghỉ việc"),
                            ("Chuyển đến", "Chuyển đến"),
                            ("Thôi việc", "Thôi việc"),
                            ("Tạm nghỉ", "Tạm nghỉ"),
                        ],
                        default="Đang làm việc",
                        max_length=50,
                        verbose_name="Trạng thái làm việc",
                    ),
                ),
                (
                    "chuong_trinh_tham_gia",
                    models.ManyToManyField(
                        blank=True,
                        related_name="giang_vien_tham_gia",
                        to="daotao.chuongtrinhdaotao",
                        verbose_name="Chương trình đào tạo tham gia",
                    ),
                ),
                (
                    "co_quan_cong_tac",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="daotao.donvidaotao",
                        verbose_name="Cơ quan công tác",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giảng viên",
                "verbose_name_plural": "Danh sách Giảng viên",
                "ordering": ["ten", "ho"],
            },
        ),
    ]
