# Generated by Django 5.2.1 on 2025-07-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0017_giangvien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giangvien",
            name="ma_can_bo",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Mã cán bộ"
            ),
        ),
    ]
