# Generated by Django 5.2.1 on 2025-07-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0018_alter_giangvien_ma_can_bo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giangvien",
            name="dien_thoai",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Điện thoại"
            ),
        ),
    ]
