# Generated by Django 5.2.1 on 2025-07-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0019_alter_giangvien_dien_thoai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giangvien",
            name="chuong_trinh_tham_gia",
        ),
        migrations.CreateModel(
            name="PhanCongGiangDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vai_tro",
                    models.CharField(
                        choices=[
                            ("CHU_TRI_XD", "Chủ trì xây dựng"),
                            ("CHU_TRI_GD", "Chủ trì giảng dạy"),
                            ("THAM_GIA_GD", "Tham gia giảng dạy"),
                        ],
                        default="THAM_GIA_GD",
                        max_length=20,
                        verbose_name="Vai trò",
                    ),
                ),
                (
                    "chi_tiet_hoc_phan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cac_phan_cong",
                        to="daotao.chitiethocphantrongctdt",
                        verbose_name="Học phần trong CTĐT",
                    ),
                ),
                (
                    "giang_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cac_phan_cong",
                        to="daotao.giangvien",
                        verbose_name="Giảng viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phân công Giảng dạy",
                "verbose_name_plural": "Các Phân công Giảng dạy",
                "unique_together": {("giang_vien", "chi_tiet_hoc_phan")},
            },
        ),
    ]
