# Generated by Django 5.2.1 on 2025-07-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0020_remove_giangvien_chuong_trinh_tham_gia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chitiethocphantrongctdt",
            name="danh_muc_kien_thuc",
        ),
        migrations.AddField(
            model_name="chitiethocphantrongctdt",
            name="temp_field",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
