# Generated by Django 5.2.1 on 2025-07-31 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0021_remove_chitiethocphantrongctdt_danh_muc_kien_thuc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chitiethocphantrongctdt",
            name="temp_field",
        ),
        migrations.AddField(
            model_name="chitiethocphantrongctdt",
            name="danh_muc_kien_thuc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="daotao.danhmuckienthuc",
                verbose_name="Phân loại trong CTĐT này",
            ),
        ),
    ]
