# Generated by Django 5.2.1 on 2025-08-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0022_remove_chitiethocphantrongctdt_temp_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="giang_vien_tham_gia",
            field=models.ManyToManyField(
                blank=True,
                related_name="chuong_trinh_tham_gia",
                to="daotao.giangvien",
                verbose_name="Giảng viên tham gia",
            ),
        ),
    ]
