# Generated by Django 5.2.1 on 2025-08-10 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0023_chuongtrinhdaotao_giang_vien_tham_gia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="decuonghocphan",
            name="ngay_phe_duyet",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ngày phê duyệt"
            ),
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="nguoi_phe_duyet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="de_cuong_da_phe_duyet",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người phê duyệt",
            ),
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="nguoi_tao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="de_cuong_da_tao",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người tạo",
            ),
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Bản nháp"),
                    ("PENDING_APPROVAL", "Chờ duyệt"),
                    ("APPROVED", "Đã phê duyệt"),
                    ("REJECTED", "Bị từ chối"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
