# Generated by Django 5.2.1 on 2025-08-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0024_decuonghocphan_ngay_phe_duyet_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decuonghocphan",
            options={
                "ordering": ["hoc_phan", "-ngay_ban_hanh"],
                "permissions": [
                    ("can_approve_decuong", "Có thể phê duyệt Đề cương học phần")
                ],
                "verbose_name": "Phiên bản Đề cương Học phần",
                "verbose_name_plural": "Các Phiên bản Đề cương Học phần",
            },
        ),
    ]
