# Generated by Django 5.2.1 on 2025-08-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0025_alter_decuonghocphan_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decuonghocphan",
            name="muc_tieu_hoc_phan",
        ),
    ]
