# Generated by Django 5.2.1 on 2025-08-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0026_remove_decuonghocphan_muc_tieu_hoc_phan"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaiLieuHocTap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_tai_lieu",
                    models.CharField(max_length=500, verbose_name="Tên tài liệu"),
                ),
                (
                    "tac_gia",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Tác giả"
                    ),
                ),
                (
                    "nha_xuat_ban",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nhà xuất bản",
                    ),
                ),
                (
                    "nam_xuat_ban",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Năm xuất bản"
                    ),
                ),
                (
                    "loai_tai_lieu",
                    models.CharField(
                        choices=[
                            ("SACH", "Sách"),
                            ("GIAO_TRINH", "Giáo trình"),
                            ("BAI_BAO", "Bài báo khoa học"),
                            ("WEBSITE", "Trang web/Tài liệu online"),
                            ("KHAC", "Khác"),
                        ],
                        default="SACH",
                        max_length=20,
                        verbose_name="Loại tài liệu",
                    ),
                ),
                (
                    "mo_ta",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mô tả/Tóm tắt"
                    ),
                ),
                (
                    "duong_dan",
                    models.URLField(
                        blank=True, null=True, verbose_name="Đường dẫn (URL)"
                    ),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tài liệu học tập",
                "verbose_name_plural": "Thư viện Tài liệu học tập",
                "ordering": ["-nam_xuat_ban", "ten_tai_lieu"],
            },
        ),
        migrations.RemoveField(
            model_name="decuonghocphan",
            name="tai_lieu_hoc_tap",
        ),
        migrations.CreateModel(
            name="DeCuongTaiLieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loai_lien_ket",
                    models.CharField(
                        choices=[
                            ("CHINH", "Tài liệu chính"),
                            ("THAM_KHAO", "Tài liệu tham khảo"),
                        ],
                        default="THAM_KHAO",
                        max_length=20,
                        verbose_name="Phân loại",
                    ),
                ),
                (
                    "de_cuong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daotao.decuonghocphan",
                    ),
                ),
                (
                    "tai_lieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daotao.tailieuhoctap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài liệu cho Đề cương",
                "verbose_name_plural": "Các Tài liệu cho Đề cương",
                "unique_together": {("de_cuong", "tai_lieu")},
            },
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="tai_lieu_hoc_tap",
            field=models.ManyToManyField(
                related_name="de_cuong_su_dung",
                through="daotao.DeCuongTaiLieu",
                to="daotao.tailieuhoctap",
                verbose_name="Tài liệu học tập",
            ),
        ),
    ]
