# Generated by Django 5.2.1 on 2025-08-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daotao",
            "0027_tailieuhoctap_remove_decuonghocphan_tai_lieu_hoc_tap_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decuonghocphan",
            name="nhiem_vu_sinh_vien",
        ),
        migrations.AlterField(
            model_name="decuonghocphan",
            name="tom_tat_noi_dung",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mô tả học phần"
            ),
        ),
    ]
