# Generated by Django 5.2.1 on 2025-08-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0028_remove_decuonghocphan_nhiem_vu_sinh_vien_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chuandaurahocphan",
            name="dap_ung_cdr_ctdt",
            field=models.ManyToManyField(
                blank=True,
                related_name="clos_dap_ung",
                to="daotao.chuandaura",
                verbose_name="Đáp ứng CĐR của CTĐT (PLO)",
            ),
        ),
        migrations.AddField(
            model_name="chuandaurahocphan",
            name="trinh_do_nang_luc",
            field=models.TextField(
                blank=True, null=True, verbose_name="Trình độ năng lực (ghi chú thêm)"
            ),
        ),
        migrations.AddField(
            model_name="chuandaurahocphan",
            name="tua",
            field=models.CharField(
                blank=True,
                choices=[("TUA", "TUA"), ("TU", "TU")],
                max_length=3,
                null=True,
                verbose_name="TUA",
            ),
        ),
    ]
