# Generated by Django 5.2.1 on 2025-08-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0029_chuandaurahocphan_dap_ung_cdr_ctdt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decuonghocphan",
            name="cac_loai_hoc_lieu_khac",
            field=models.TextField(
                blank=True, null=True, verbose_name="Các loại học liệu khác"
            ),
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="giang_vien_bien_soan",
            field=models.ManyToManyField(
                blank=True,
                related_name="de_cuong_bien_soan",
                to="daotao.giangvien",
                verbose_name="Giảng viên biên soạn",
            ),
        ),
        migrations.AddField(
            model_name="decuonghocphan",
            name="quy_dinh_hoc_phan",
            field=models.TextField(
                blank=True, null=True, verbose_name="Các quy định của học phần"
            ),
        ),
        migrations.AddField(
            model_name="noidungchitietdecuong",
            name="ky_nang_thai_do",
            field=models.TextField(
                blank=True, null=True, verbose_name="Kỹ năng mềm và thái độ"
            ),
        ),
    ]
