# Generated by Django 5.2.1 on 2025-08-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0030_decuonghocphan_cac_loai_hoc_lieu_khac_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tailieuhoctap",
            options={
                "ordering": ["-nam_xuat_ban", "nhan_de"],
                "verbose_name": "Tài liệu học tập",
                "verbose_name_plural": "Kho Tài liệu học tập",
            },
        ),
        migrations.RemoveField(
            model_name="tailieuhoctap",
            name="mo_ta",
        ),
        migrations.RemoveField(
            model_name="tailieuhoctap",
            name="ten_tai_lieu",
        ),
        migrations.AddField(
            model_name="tailieuhoctap",
            name="cutter",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Chỉ số Cutter"
            ),
        ),
        migrations.AddField(
            model_name="tailieuhoctap",
            name="dewey",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phân loại Dewey"
            ),
        ),
        migrations.AddField(
            model_name="tailieuhoctap",
            name="ngon_ngu",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ngôn ngữ"
            ),
        ),
        migrations.AddField(
            model_name="tailieuhoctap",
            name="nhan_de",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Nhan đề"
            ),
        ),
        migrations.AddField(
            model_name="tailieuhoctap",
            name="noi_xuat_ban",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nơi xuất bản"
            ),
        ),
        migrations.AddField(
            model_name="tailieuhoctap",
            name="tom_tat",
            field=models.TextField(blank=True, null=True, verbose_name="Tóm tắt"),
        ),
    ]
