# Generated by Django 5.2.1 on 2025-08-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0031_alter_tailieuhoctap_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tailieuhoctap",
            name="oai_identifier",
            field=models.CharField(
                blank=True,
                max_length=191,
                null=True,
                unique=True,
                verbose_name="OAI Identifier",
            ),
        ),
    ]
