# Generated by Django 5.2.1 on 2025-08-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0032_tailieuhoctap_oai_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="tailieuhoctap",
            name="bib_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="BIB ID from external API",
            ),
        ),
    ]
