# Generated by Django 5.2.1 on 2025-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daotao", "0033_tailieuhoctap_bib_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chuongtrinhdaotao",
            options={
                "ordering": ["ten_nganh_ctdt"],
                "permissions": [
                    ("can_approve_ctdt", "Có thể phê duyệt Chương trình Đào tạo"),
                    ("can_reject_ctdt", "Có thể yêu cầu chỉnh sửa/từ chối CTĐT"),
                    ("can_submit_for_approval", "Có thể gửi duyệt CTĐT"),
                    ("can_create_new_version", "Có thể tạo phiên bản mới cho CTĐT"),
                    ("can_archive_ctdt", "Có thể lưu trữ một CTĐT cũ"),
                    (
                        "can_manage_program_structure",
                        "Có thể quản lý cấu trúc CTĐT (PO, PLO, học phần)",
                    ),
                    ("can_approve_cdr", "Có thể phê duyệt Chuẩn đầu ra"),
                    ("can_reject_cdr", "Có thể yêu cầu chỉnh sửa/từ chối CĐR"),
                    ("can_submit_cdr_for_approval", "Có thể gửi duyệt CĐR"),
                ],
                "verbose_name": "Chương trình Đào tạo",
                "verbose_name_plural": "Các Chương trình Đào tạo",
            },
        ),
        migrations.AddField(
            model_name="chuongtrinhdaotao",
            name="trang_thai_cdr",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Bản nháp"),
                    ("PENDING_APPROVAL", "Chờ duyệt"),
                    ("APPROVED", "Đã phê duyệt"),
                    ("REJECTED", "Bị từ chối"),
                    ("ARCHIVED", "Lưu trữ"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Trạng thái CĐR",
            ),
        ),
        migrations.AlterField(
            model_name="chuongtrinhdaotao",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Bản nháp"),
                    ("PENDING_APPROVAL", "Chờ duyệt"),
                    ("APPROVED", "Đã phê duyệt"),
                    ("REJECTED", "Bị từ chối"),
                    ("ARCHIVED", "Lưu trữ"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Trạng thái CTĐT",
            ),
        ),
    ]
